# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='destination',
        ),
    ]
