# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0005_auto_20170831_1837'),
        ('travelbud', '0002_auto_20170831_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trippers', to='loginreg.User')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(default='something', max_length=1000),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default='none'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default='none'),
        ),
        migrations.AddField(
            model_name='trip',
            name='tripper',
            field=models.ForeignKey(default='something', on_delete=django.db.models.deletion.CASCADE, related_name='trips_left', to='loginreg.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='other_trippers',
            field=models.ManyToManyField(related_name='trippers_left', to='travelbud.Tripper'),
        ),
    ]
