# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud', '0003_auto_20170831_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
