# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud', '0005_auto_20170831_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
    ]
