# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0005_auto_20170831_1837'),
        ('travelbud', '0010_auto_20170831_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(default='something', max_length=1000)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('other_trippers', models.ManyToManyField(related_name='trippers_left', to='travelbud.Tripper')),
                ('tripper', models.ForeignKey(default='something', on_delete=django.db.models.deletion.CASCADE, related_name='trips_left', to='loginreg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='other_trippers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tripper',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
