# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud', '0011_auto_20170831_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trippper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(default='something', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='other_trippers',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='tripper',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
