# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud', '0012_auto_20170831_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tripper',
            name='name',
        ),
        migrations.DeleteModel(
            name='Trippper',
        ),
        migrations.DeleteModel(
            name='Tripper',
        ),
    ]
