# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_planner', to='loginreg.User')),
                ('travelers', models.ManyToManyField(related_name='trip_travelers', to='loginreg.User')),
            ],
        ),
    ]
