# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeApp', '0002_auto_20161011_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='poke',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
