# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='user_level1',
        ),
    ]
