# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20170903_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_att',
            new_name='created_at',
        ),
    ]
