# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20170905_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description1',
            new_name='description',
        ),
    ]
